### ISSUE TITLE
爬到的数据是真实数据吗？

### ISSUE THREAD

**Issue by guoyiheng** [XNAL/vue-github-rank#1]
你好，我clone下来跑了测试，结果本地的表并没有发生变化啊

**Comment by XNAL** [comment]
是真实的数据，但是是设定了爬取时间和爬取间隔的，爬取后的数据会保存到数据库中。在/server/timer/timeTask.js文件中可以查看爬取时间设置。

**Comment by guoyiheng** [comment]
懂了，谢谢啦，就是说我要一直挂着爬取，要不然就是修改爬取时间==，谢谢你

**Comment by guoyiheng** [comment]
定时任务开始执行! 2018-04-18 19:00:00
开始进行Python数据的获取：
获取Python的第10页面数据失败.
获取Python的第10页面数据失败.
获取Python的第10页面数据失败.
获取Python的第10页面数据失败.
获取Python的第10页面数据失败.
获取Python的第10页面数据失败.
获取Python的第10页面数据失败.
获取Python的第10页面数据失败.
获取Python的第10页面数据失败.
获取Python的第10页面数据失败.
获取Python的第10页面数据失败.
获取Python的第10页面数据失败.
获取Python的第10页面数据失败.
获取Python的第10页面数据失败.
获取Python的第10页面数据失败.
获取Python的第10页面数据失败.
(node:8020) UnhandledPromiseRejectionWarning: Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x8D\xB0\xE2\x9C...' for column 'introduction' at row 6
    at Query.Sequence._packetToError (D:\origincode\vue-github-rank-master\node_modules\_mysql@2.15.0@mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (D:\origincode\vue-github-rank-master\node_modules\_mysql@2.15.0@mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (D:\origincode\vue-github-rank-master\node_modules\_mysql@2.15.0@mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (D:\origincode\vue-github-rank-master\node_modules\_mysql@2.15.0@mysql\lib\protocol\Parser.js:76:12)    at Protocol.write (D:\origincode\vue-github-rank-master\node_modules\_mysql@2.15.0@mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\origincode\vue-github-rank-master\node_modules\_mysql@2.15.0@mysql\lib\Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (D:\origincode\vue-github-rank-master\node_modules\_mysql@2.15.0@mysql\lib\protocol\Protocol.js:145:48)
    at PoolConnection.query (D:\origincode\vue-github-rank-master\node_modules\_mysql@2.15.0@mysql\lib\Connection.js:208:25)
    at D:\origincode\vue-github-rank-master\server\config\mysql-async.js:18:20
    at Ping.onOperationComplete [as _callback] (D:\origincode\vue-github-rank-master\node_modules\_mysql@2.15.0@mysql\lib\Pool.js:110:5)
    at Ping.Sequence.end (D:\origincode\vue-github-rank-master\node_modules\_mysql@2.15.0@mysql\lib\protocol\sequences\Sequence.js:88:24)
    at Ping.Sequence.OkPacket (D:\origincode\vue-github-rank-master\node_modules\_mysql@2.15.0@mysql\lib\protocol\sequences\Sequence.js:97:8)
    at Protocol._parsePacket (D:\origincode\vue-github-rank-master\node_modules\_mysql@2.15.0@mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (D:\origincode\vue-github-rank-master\node_modules\_mysql@2.15.0@mysql\lib\protocol\Parser.js:76:12)    at Protocol.write (D:\origincode\vue-github-rank-master\node_modules\_mysql@2.15.0@mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\origincode\vue-github-rank-master\node_modules\_mysql@2.15.0@mysql\lib\Connection.js:103:28)
(node:8020) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8020) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by guoyiheng** [comment]
老哥，这个是什么错误，请教

**Comment by XNAL** [comment]
`introduction `字段存储emoj表情出错，你看下你设置的字符集是utf8mb4不

**Comment by guoyiheng** [comment]
是的呀，因为是用你的建表语句建的，我也检查了，确实是

**Comment by guoyiheng** [comment]
我一步一步来的呀，感觉也没啥问题，是不是有个小步骤你漏写了

**Comment by guoyiheng** [comment]
这又提示，date too lang for topics，可以把你最近的一次sql导出来我试一下吗
